"""Add Google Places fields

Revision ID: 045e44937e93
Revises: ca2cf8fe9a82
Create Date: 2026-06-26 12:43:05.926864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045e44937e93'
down_revision = 'ca2cf8fe9a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('personal_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_user_restaurants_restaurant_id_restaurants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_restaurants_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'restaurant_id', name='unique_user_restaurant')
    )
    op.create_table('event_restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_restaurants_event_id_events')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_event_restaurants_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('radius_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_events_selected_restaurant_id_restaurants', type_='foreignkey')
        batch_op.drop_column('selected_restaurant_id')
        batch_op.drop_column('location_filter')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_place_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('photo_refs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cuisine_override', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cuisine_tags', sa.JSON(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint('unique_user_restaurant', type_='unique')
        batch_op.create_unique_constraint(None, ['google_place_id'])
        batch_op.drop_constraint('fk_restaurants_suggested_by_users', type_='foreignkey')
        batch_op.drop_column('location')
        batch_op.drop_column('status')
        batch_op.drop_column('cuisine')
        batch_op.drop_column('suggested_by')
        batch_op.drop_column('price_range')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_range', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('suggested_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cuisine', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_restaurants_suggested_by_users', 'users', ['suggested_by'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('unique_user_restaurant', ['name', 'location', 'suggested_by'])
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('cuisine_tags')
        batch_op.drop_column('cuisine_override')
        batch_op.drop_column('photo_refs')
        batch_op.drop_column('price_level')
        batch_op.drop_column('website')
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')
        batch_op.drop_column('address')
        batch_op.drop_column('google_place_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_filter', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('selected_restaurant_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_events_selected_restaurant_id_restaurants', 'restaurants', ['selected_restaurant_id'], ['id'])
        batch_op.drop_column('location_name')
        batch_op.drop_column('radius_km')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.drop_table('event_restaurants')
    op.drop_table('user_restaurants')
    # ### end Alembic commands ###
