"""add radius_km to events

Revision ID: 1faba291f7bc
Revises: 97e18fb2b3d9
Create Date: 2026-06-20 20:51:03.108053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1faba291f7bc'
down_revision = '97e18fb2b3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radius_km', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('radius_km')

    # ### end Alembic commands ###
