"""change price_range to integer

Revision ID: 75425fab5218
Revises: 2c0ab0128fd0
Create Date: 2026-03-21 17:54:43.508897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75425fab5218'
down_revision = '2c0ab0128fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('price_range',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('price_range',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
