"""add cuisine tags to restaurants

Revision ID: 97e18fb2b3d9
Revises: 6ee73faf4f2b
Create Date: 2026-06-20 16:37:51.196156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e18fb2b3d9'
down_revision = '6ee73faf4f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine_tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('cuisine_tags')

    # ### end Alembic commands ###
