"""baseline

Revision ID: ca2cf8fe9a82
Revises: 
Create Date: 2026-06-04 13:25:00.914469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2cf8fe9a82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('price_range', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('suggested_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['suggested_by'], ['users.id'], name=op.f('fk_restaurants_suggested_by_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'location', 'suggested_by', name='unique_user_restaurant')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('cuisine_filter', sa.String(), nullable=True),
    sa.Column('location_filter', sa.String(), nullable=True),
    sa.Column('price_filter', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('selected_restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_events_created_by_users')),
    sa.ForeignKeyConstraint(['selected_restaurant_id'], ['restaurants.id'], name=op.f('fk_events_selected_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('rsvp_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_participants_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_participants_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='unique_event_participant')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_participants')
    op.drop_table('events')
    op.drop_table('restaurants')
    op.drop_table('users')
    # ### end Alembic commands ###
