"""refactor to google places + junction tables

Revision ID: fe7c8c0b8b83
Revises: 75425fab5218
Create Date: 2026-05-02 13:20:16.267164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7c8c0b8b83'
down_revision = '75425fab5218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_selected_restaurant_id_restaurants', type_='foreignkey')
        batch_op.drop_column('selected_restaurant_id')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_place_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('photo_refs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cuisine_override', sa.String(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint('unique_user_restaurant', type_='unique')
        batch_op.create_unique_constraint(None, ['google_place_id'])
        batch_op.drop_constraint('fk_restaurants_suggested_by_users', type_='foreignkey')
        batch_op.drop_column('cuisine')
        batch_op.drop_column('suggested_by')
        batch_op.drop_column('price_range')
        batch_op.drop_column('status')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('price_range', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('suggested_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cuisine', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_restaurants_suggested_by_users', 'users', ['suggested_by'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('unique_user_restaurant', ['name', 'location', 'suggested_by'])
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('cuisine_override')
        batch_op.drop_column('photo_refs')
        batch_op.drop_column('website')
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')
        batch_op.drop_column('address')
        batch_op.drop_column('google_place_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_restaurant_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_events_selected_restaurant_id_restaurants', 'restaurants', ['selected_restaurant_id'], ['id'])

    # ### end Alembic commands ###
